language: java
sudo: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/

addons:
    apt:
        packages:
        - rpm
        - fakeroot

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      jdk: openjdk11
    - os: linux
      dist: trusty
      jdk: oraclejdk11
    - os: osx
      jdk: openjdk11
      osx_image: xcode9.4
    - os: osx
      jdk: oraclejdk11
      osx_image: xcode9.4
    - os: osx
      jdk: openjdk11
      osx_image: xcode10

before_script:
  - |
    if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
      brew upgrade openssl@1.1
      export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"
      openssl version
    fi

# skip install stage.
install: true

script: ./gradlew build --no-daemon -Pjavapackager.debug=true -PTEST_PACKAGER_DMG=false

notifications:
  email: false
