version: "{branch} {build}"

image: Visual Studio 2017

environment:
  JAVA_HOME: C:\\jdk11
  VCINSTALLDIR: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build
  APPVEYOR_CACHE_ENTRY_ZIP_ARGS: "-t7z -m0=lzma -mx=9"

shallow_clone: true

build_script:
  - ps: |
      choco install wixtoolset --no-progress
      choco install cmake --installargs 'ADD_CMAKE_TO_PATH=""User""'` --no-progress --pre --dir C:\Users\Appveyor\cmake
      $client = New-Object net.webclient
      $client.DownloadFile('http://jdk.java.net/11/', 'C:\Users\appveyor\openjdk11.html')
      $openJdk11 = cat C:\Users\appveyor\openjdk11.html | where { $_ -match "href.*https://download.java.net.*jdk11.*windows-x64.*zip\`"" } | %{ $_ -replace "^.*https:", "https:" } | %{ $_ -replace ".zip\`".*$", ".zip" }
      echo "Download boot JDK from: $openJdk11"
      $client.DownloadFile($openJdk11, 'C:\Users\appveyor\openjdk11.zip')
      Expand-Archive -Path 'C:\Users\appveyor\openjdk11.zip' -DestinationPath 'C:\Users\appveyor\openjdk11'
      Copy-Item -Path 'C:\Users\appveyor\openjdk11\*\' -Destination 'C:\jdk11' -Recurse -Force
      refreshenv
      mkdir build
      cd build
      $env:PATH += ";C:\Users\Appveyor\cmake\bin"
      cmake -G "Visual Studio 15 2017" -A x64 -T host=x64 ..
      cmake --build . --config Release
      cd ..
  - cmd: .\gradlew build --no-daemon --warning-mode all
  - ps: |
       $env:PATH = "${env:JAVA_HOME}\bin;${env:PATH};C:\Program Files (x86)\WiX Toolset v3.11\bin"
       cd modules\jdk.packager
       $env:JAVAPACKAGER_DEBUG="true"
       build\generated-resources\com\sun\openjfx\tools\packager\windows\javapackager.exe -deploy -v -native -outdir build\minesweeper -name MinesweeperFX -BappResources="..\..\modules\minesweeperfx\build\libs" -BsignBundle=false -Bversion=9 --module minesweeperfx/minesweeperfx.MinesweeperFX --module-path "..\..\modules\minesweeperfx\build\libs;..\..\modules\jdk.packager\build\deps;..\..\modules\jdk.packager.services\build\libs" -appClass minesweeperfx.MinesweeperFX
       cd ..\..
on_success:
  - ps: |
        $buildZip = "build.zip"
        Compress-Archive -Path ".\build", ".\modules\jdk.packager\build", ".\modules\jdk.packager.services\build" -DestinationPath $buildZip -CompressionLevel Optimal
        Push-AppveyorArtifact $buildZip -Verbose

cache:
  - C:\Users\appveyor\.gradle\caches
  - '%JAVA_HOME% -> appveyor.yml'
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
