version: "{branch} {build}"

image: Visual Studio 2017

environment:
  JAVA_HOME: C:\\jdk11
  VCINSTALLDIR: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build
  APPVEYOR_CACHE_ENTRY_ZIP_ARGS: "-t7z -m0=lzma -mx=9"

shallow_clone: true

build_script:
  - ps: |
      choco install cmake --installargs 'ADD_CMAKE_TO_PATH=""User""'` --no-progress --pre --dir C:\Users\Appveyor\cmake
      $client = New-Object net.webclient
      $client.DownloadFile('http://jdk.java.net/11/', 'C:\Users\appveyor\openjdk11.html')
      $openJdk11 = cat C:\Users\appveyor\openjdk11.html | where { $_ -match "href.*https://download.java.net.*jdk11.*windows-x64.*zip\`"" } | %{ $_ -replace "^.*https:", "https:" } | %{ $_ -replace ".zip\`".*$", ".zip" }
      echo "Download boot JDK from: $openJdk11"
      $client.DownloadFile($openJdk11, 'C:\Users\appveyor\openjdk11.zip')
      Expand-Archive -Path 'C:\Users\appveyor\openjdk11.zip' -DestinationPath 'C:\Users\appveyor\openjdk11'
      Copy-Item -Path 'C:\Users\appveyor\openjdk11\*\' -Destination 'C:\jdk11' -Recurse -Force
      refreshenv
      mkdir build
      cd build
      $env:PATH += ";C:\Users\Appveyor\cmake\bin"
      cmake ..
      cmake --build . --config Release
      cd Release
      $artifacts = @("javapackager.exe", "WinLauncher.exe", "WinLauncherSvc.exe", "packager.dll")
      New-Item -Force ..\..\modules\jdk.packager\build\generated-resources\com\sun\openjfx\tools\packager\windows -ItemType "directory"
      foreach ($artifact in $artifacts) {
        Copy-Item $artifact -Destination ..\..\modules\jdk.packager\build\generated-resources\com\sun\openjfx\tools\packager\windows -Force
      }
      cd ..\..
  - cmd: .\gradlew build --no-daemon --warning-mode all

on_success:
  - ps: |
        $buildZip = "build.zip"
        Compress-Archive -Path ".\build", ".\modules\jdk.packager\build", ".\modules\jdk.packager.services\build" -DestinationPath $buildZip -CompressionLevel Optimal
        Push-AppveyorArtifact $buildZip -Verbose

cache:
  - C:\Users\appveyor\.gradle\caches
  - '%JAVA_HOME% -> appveyor.yml'
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
