version: "{branch} {build}"

image: Visual Studio 2017

environment:
  JAVA_HOME: C:\\jdk11
  VCINSTALLDIR: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build
  APPVEYOR_CACHE_ENTRY_ZIP_ARGS: "-t7z -m0=lzma -mx=9"

shallow_clone: true

build_script:
  - ps: |
      $client = New-Object net.webclient
      $client.DownloadFile('http://jdk.java.net/11/', 'C:\Users\appveyor\openjdk11.html')
      $openJdk11 = cat C:\Users\appveyor\openjdk11.html | where { $_ -match "href.*https://download.java.net.*jdk11.*windows-x64.*zip\`"" } | %{ $_ -replace "^.*https:", "https:" } | %{ $_ -replace ".zip\`".*$", ".zip" }
      echo "Download boot JDK from: $openJdk11"
      $client.DownloadFile($openJdk11, 'C:\Users\appveyor\openjdk11.zip')
      Expand-Archive -Path 'C:\Users\appveyor\openjdk11.zip' -DestinationPath 'C:\Users\appveyor\openjdk11'
      Copy-Item -Path 'C:\Users\appveyor\openjdk11\*\' -Destination 'C:\jdk11' -Recurse -Force
      choco install gradle --version 4.10.2
      $msvcToolsVer = Get-Content "$env:VCINSTALLDIR\Microsoft.VCToolsVersion.default.txt"
      if ([string]::IsNullOrWhitespace($msvcToolsVer)) {
        # The MSVC tools version file can have txt *or* props extension.
        $msvcToolsVer = Get-Content "$env:VCINSTALLDIR\Microsoft.VCToolsVersion.default.props"
      }
      $env:MSVC_VER = $msvcToolsVer
      $env:VS150COMNTOOLS = $env:VCINSTALLDIR
      $env:VSVARS32FILE = "$env:VCINSTALLDIR\vcvars32.bat"
      refreshenv
  - cmd: gradle build --no-daemon --warning-mode all

on_success:
  - ps: |
        $buildZip = "build.zip"
        Compress-Archive -Path ".\build", ".\modules\jdk.packager\build", ".\modules\jdk.packager.services\build" -DestinationPath $buildZip -CompressionLevel Optimal
        Push-AppveyorArtifact $buildZip -Verbose

cache:
  - C:\Users\appveyor\.gradle\caches
  - '%JAVA_HOME% -> appveyor.yml'
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
